#!/usr/bin/env bash
set -euo pipefail
#
# sync-pack.sh — write the canonical aeon-atrium-skills pack into THIS repo, then
# commit + push. Run from the root of a clone/codespace of
# Atrium-Hermes/aeon-atrium-skills:  bash sync-pack.sh
#
# Full snapshot (idempotent): brings the live pack to exactly match upstream source,
# including the post-process spend pattern, scanner-clean SKILL.md, and atrium-attest.
[ -f skills-pack.json ] || { echo "Run from the root of the aeon-atrium-skills pack repo." >&2; exit 1; }

cat > LICENSE <<'ATRIUM_SYNC_EOF_0'
MIT License

Copyright (c) 2026 Atrium-Hermes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
ATRIUM_SYNC_EOF_0
cat > README.md <<'ATRIUM_SYNC_EOF_1'
# Atrium Skills — an Aeon skill pack

Publish, monetize, and discover agent skills on **[Atrium](https://atriumhermes.tech)**
— the onchain skill marketplace on Base — straight from an [Aeon](https://www.aeon.fun)
agent. Turn the skills your agent evolves into provenance-signed, USDC-earning assets,
and rent the ones it's missing.

## Install
```bash
./install-skill-pack <your-github-owner>/aeon-atrium-skills
```
Skills install **disabled by default** — enable the ones you want in `aeon.yml`.

## Skills
| Skill | What it does | Schedule | Secrets |
|---|---|---|---|
| `atrium-publish` | Publish queued/evolved skills to Atrium (DID-signed, IPFS, priced in USDC) so they earn per call. Declares prior versions as royalty parents for evolutions. | `0 13 * * *` | `ATRIUM_PRIVATE_KEY`, `PINATA_JWT` |
| `atrium-scout` | Search Atrium for skills matching your open loops/goals; recommend (or, if enabled, invoke) what's worth renting. Read-only by default. | `0 11 * * *` | optional `ATRIUM_PRIVATE_KEY` |
| `atrium-earnings` | Track creator earnings and **auto-withdraw USDC daily** when withdrawable ≥ `ATRIUM_WITHDRAW_THRESHOLD_USDC` (default `1`); folds totals into the brief. Set the threshold before enabling, or pass `report-only` to skip the sweep. | `0 14 * * *` | `ATRIUM_PRIVATE_KEY` |
| `atrium-attest` | Turn this agent's real 1–5 run-quality scores into **onchain benchmark attestations** for the skills it published — a reputation signal `atrium-scout` (and the marketplace) can rank by. Queues; the tx runs in post-process. | `0 15 * * 1` | `ATRIUM_PRIVATE_KEY` |

Chain them for a self-sustaining loop: **scout → publish → earnings → attest** (discover, monetize, sweep, and prove quality onchain).

## Secrets
- `ATRIUM_PRIVATE_KEY` — the agent's EVM key (its Atrium wallet; needs a little Base ETH for gas + USDC to invoke). Generated by `atrium init`.
- `PINATA_JWT` — IPFS pinning JWT (publish only). Free at pinata.cloud.
- Optional: `ATRIUM_DEFAULT_PRICE_USDC`, `ATRIUM_WITHDRAW_THRESHOLD_USDC`.

The skills install the `atrium` CLI on first run from npm, pinned to a published
version: `npm i -g @atrium-hermes/cli@0.1.0` (no live curl-pipe-bash). They
read/write `~/.atrium/.env`. Discovery uses the public, read-only indexer API (no key).

## Spending: the post-process step (required for renting)

Aeon deliberately keeps secrets **out of the Claude/model step**, so a skill cannot
spend (`atrium invoke`/`publish`/`withdraw`) inline — the wallet key isn't there. Every
spending skill therefore **queues** its intent during the model step, and the actual
on-chain action happens afterwards in **`scripts/postprocess-atrium.sh`** (Aeon
auto-runs `scripts/postprocess-*.sh` after Claude, with full env). One script handles
all four queues:

| Skill | Queues to | Post-process does |
|---|---|---|
| `atrium-scout` | `.pending-atrium/<slug>.json` | `atrium invoke` (one rental/run, honours `auto_invoke` + `max_price_usdc`) |
| `atrium-publish` | `.pending-atrium-publish/<slug>.json` (+ staged `skill.md`) | `atrium publish` → records to `published.json` |
| `atrium-earnings` | `.pending-atrium-earnings/withdraw.json` | `atrium withdraw` if withdrawable ≥ `threshold` → records to `earnings.json` |
| `atrium-attest` | `.pending-atrium-attest/<id>.json` | `atrium attest` (tx-only, gas) → records to `attested.json` |

Two one-time setup steps:

1. **Copy the script** `scripts/postprocess-atrium.sh` (shipped in this pack) into your
   Aeon repo at the same path. It no-ops when no key is set (report-only), honours
   `auto_invoke` + `max_price_usdc`, rents at most one skill per run, and is safe to
   re-run (each queue dir is drained idempotently).
2. **Wire the secrets into the post-process step** in `.github/workflows/aeon.yml` — add
   to that step's `env:` (NOT the Claude step):
   ```yaml
   ATRIUM_PRIVATE_KEY: ${{ secrets.ATRIUM_PRIVATE_KEY }}
   PINATA_JWT: ${{ secrets.PINATA_JWT }}   # required if you publish
   ```

Then set `auto_invoke: true` in `memory/atrium/scout-config.md` once the wallet is
funded. (`atrium-publish` and `atrium-earnings` now spend via this same post-process
path — they only stage + queue in the model step.)

## How it composes with Aeon
Aeon generates and evolves skills; Atrium gives them identity, a market, and a
revenue line. `atrium-publish` is the "earn from what you learn" loop — every stable
skill from Aeon's self-improve cycle becomes a USDC-earning, onchain asset, with the
prior version earning royalties on its descendants.

## Links
- Atrium: https://atriumhermes.tech · docs `/docs` · whitepaper `/whitepaper`
- Registry (Base mainnet, verified): `0xA713c88927523279B874640003Ed697e509732a7`
- Aeon: https://www.aeon.fun · https://github.com/aaronjmars/aeon

MIT.
ATRIUM_SYNC_EOF_1
cat > skills-pack.json <<'ATRIUM_SYNC_EOF_2'
{
  "name": "Atrium Skills",
  "version": "0.1.0",
  "description": "Publish, monetize, and discover agent skills on Atrium — the onchain skill marketplace on Base. Turn an Aeon agent's evolving skills into provenance-signed, USDC-earning assets.",
  "author": "Atrium-Hermes",
  "license": "MIT",
  "homepage": "https://atriumhermes.tech",
  "skills": [
    {
      "slug": "atrium-publish",
      "path": "skills/atrium-publish",
      "description": "Publish skills your agent created or evolved to Atrium — DID-signed, pinned to IPFS, priced in USDC — so they earn per call.",
      "category": "crypto",
      "schedule": "0 13 * * *",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY", "PINATA_JWT"],
      "secrets_optional": ["ATRIUM_DEFAULT_PRICE_USDC"],
      "capabilities": ["onchain_writes", "external_api", "writes_external_host"]
    },
    {
      "slug": "atrium-scout",
      "path": "skills/atrium-scout",
      "description": "Scan the Atrium marketplace for skills that match your agent's open loops and goals, and recommend (or invoke) the ones worth renting.",
      "category": "crypto",
      "schedule": "0 11 * * *",
      "default_enabled": false,
      "secrets_optional": ["ATRIUM_PRIVATE_KEY"],
      "capabilities": ["external_api", "read_only"]
    },
    {
      "slug": "atrium-earnings",
      "path": "skills/atrium-earnings",
      "description": "Track your Atrium creator earnings, withdraw USDC once it clears a threshold, and report it in the brief. Note: runs daily and AUTO-WITHDRAWS to your wallet whenever withdrawable ≥ ATRIUM_WITHDRAW_THRESHOLD_USDC (default 1) — set this env var before enabling to control sweep frequency, or pass `report-only` to skip withdrawal. Withdraw only ever sends to your own wallet.",
      "category": "crypto",
      "schedule": "0 14 * * *",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY"],
      "secrets_optional": ["ATRIUM_WITHDRAW_THRESHOLD_USDC"],
      "capabilities": ["onchain_writes", "sends_notifications"]
    },
    {
      "slug": "atrium-attest",
      "path": "skills/atrium-attest",
      "description": "Turn this agent's real 1-5 run-quality scores into onchain Atrium benchmark attestations for the skills it published — a reputation signal the marketplace can rank by. Queues the attestation; the spend/tx runs in scripts/postprocess-atrium.sh (key stays out of the model step).",
      "category": "crypto",
      "schedule": "0 15 * * 1",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY"],
      "capabilities": ["onchain_writes"]
    }
  ]
}
ATRIUM_SYNC_EOF_2
mkdir -p scripts
cat > scripts/postprocess-atrium.sh <<'ATRIUM_SYNC_EOF_3'
#!/usr/bin/env bash
# Post-process Atrium rental requests queued by the atrium-scout skill.
#
# WHY THIS EXISTS: Aeon keeps secrets (ATRIUM_PRIVATE_KEY) OUT of the Claude/model
# step by design, so a skill can't spend inline. Instead atrium-scout writes its
# top pick to .pending-atrium/<slug>.json, and THIS script — which Aeon runs after
# Claude (via the post-process step, with full env) — performs the on-chain
# `atrium invoke` (USDC spend) and stashes the body.
#
# SETUP (one-time, in your Aeon repo):
#   1. Copy this file to scripts/postprocess-atrium.sh (Aeon auto-runs scripts/postprocess-*.sh).
#   2. Add to the post-process step env in .github/workflows/aeon.yml:
#        ATRIUM_PRIVATE_KEY: ${{ secrets.ATRIUM_PRIVATE_KEY }}
#      (keep it OUT of the Claude step — model never sees the key.)
#
# Safety: no key -> no-op (report-only). Honours auto_invoke + max_price_usdc from
# memory/atrium/scout-config.md. Skips already-rented skills. One rental per run.
set -euo pipefail

PENDING_DIR=".pending-atrium"
RENTED_DIR="memory/atrium/rented"
CONFIG="memory/atrium/scout-config.md"

# No key -> report-only no-op for every block below (invoke/publish/withdraw/attest all
# need the wallet). This is the ONLY global early-exit; per-queue guards follow so an
# empty rental queue never blocks publish/withdraw/attest (they're independent skills).
[ -n "${ATRIUM_PRIVATE_KEY:-}" ] || { echo "atrium-postprocess: ATRIUM_PRIVATE_KEY not set, skipping (report-only)"; exit 0; }

# Ensure the CLI once — all four queue blocks use it.
command -v atrium >/dev/null 2>&1 || { echo "atrium-postprocess: installing atrium CLI..."; npm install -g @atrium-hermes/cli >/dev/null 2>&1 || { echo "atrium-postprocess: CLI install failed"; exit 0; }; }

# ── Rentals queued by atrium-scout (.pending-atrium/<slug>.json) ──
if [ -d "$PENDING_DIR" ] && ls -A "$PENDING_DIR"/*.json >/dev/null 2>&1; then
  AUTO_INVOKE="false"; MAX_PRICE="0"
  if [ -f "$CONFIG" ]; then
    AUTO_INVOKE=$(grep -E '^auto_invoke:' "$CONFIG" | head -1 | sed -E 's/^auto_invoke:[[:space:]]*//; s/[[:space:]]*#.*//' || echo false)
    MAX_PRICE=$(grep -E '^max_price_usdc:' "$CONFIG" | head -1 | sed -E 's/^max_price_usdc:[[:space:]]*//; s/[[:space:]]*#.*//' || echo 0)
  fi
  if [ "$AUTO_INVOKE" != "true" ]; then
    echo "atrium-postprocess: auto_invoke is '$AUTO_INVOKE', not renting"
  else
    mkdir -p "$RENTED_DIR"
    for req in "$PENDING_DIR"/*.json; do
      [ -f "$req" ] || continue
      SKILL_ID=$(jq -r '.skillId // empty' "$req"); SLUG=$(jq -r '.slug // empty' "$req")
      PRICE=$(jq -r '.price // "0"' "$req"); NETWORK=$(jq -r '.network // "base"' "$req")
      [ -n "$SKILL_ID" ] && [ -n "$SLUG" ] || { echo "atrium-postprocess: bad request $(basename "$req"), skipping"; continue; }
      [ -f "$RENTED_DIR/$SLUG.md" ] && { echo "atrium-postprocess: $SLUG already rented"; rm -f "$req"; continue; }
      awk -v p="$PRICE" -v c="$MAX_PRICE" 'BEGIN{exit !(p+0 > c+0)}' && { echo "atrium-postprocess: $SLUG price $PRICE > cap $MAX_PRICE, skipping"; continue; }

      echo "atrium-postprocess: invoking $SLUG ($SKILL_ID) at \$$PRICE on $NETWORK..."
      # Balance/allowance are enforced on-chain by invoke (it reverts if short), so we
      # don't pre-gate on `atrium balance` (its non-zero exit must never block a funded wallet).
      atrium balance --network "$NETWORK" 2>/dev/null || echo "atrium-postprocess: balance query unavailable, proceeding (invoke enforces funds on-chain)"
      OUT=$(atrium invoke "$SKILL_ID" --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: invoke failed for $SLUG:"; echo "$OUT"; continue; }
      echo "$OUT"
      TX=$(echo "$OUT" | grep -oE '0x[a-fA-F0-9]{64}' | head -1 || echo "")
      BODY=$(atrium fetch "$SKILL_ID" --network "$NETWORK" 2>/dev/null || echo "")
      { echo "# $SLUG (rented from Atrium)"; echo; echo "- skillId: \`$SKILL_ID\`"; echo "- price: \$$PRICE USDC"; echo "- tx: ${TX:-see run logs}"; echo; echo "---"; echo; echo "$BODY"; } > "$RENTED_DIR/$SLUG.md"
      echo "atrium-postprocess: saved body to $RENTED_DIR/$SLUG.md"
      rm -f "$req"
      break   # one rental per run
    done
  fi
fi

# ── Reputation attestations queued by atrium-attest (.pending-atrium-attest/*.json) ──
# These are tx-only (no USDC spend) but need ETH for gas; safe to run unconditionally.
ATTEST_DIR=".pending-atrium-attest"; ATTESTED="memory/atrium/attested.json"
if [ -d "$ATTEST_DIR" ] && ls -A "$ATTEST_DIR"/*.json >/dev/null 2>&1; then
  [ -f "$ATTESTED" ] && jq empty "$ATTESTED" 2>/dev/null || echo '{}' > "$ATTESTED"
  for req in "$ATTEST_DIR"/*.json; do
    [ -f "$req" ] || continue
    SKILL_ID=$(jq -r '.skillId // empty' "$req"); RATE=$(jq -r '.successRate // empty' "$req")
    SAMPLES=$(jq -r '.sampleCount // empty' "$req"); ROOT=$(jq -r '.merkleRoot // empty' "$req")
    NETWORK=$(jq -r '.network // "base"' "$req")
    [ -n "$SKILL_ID" ] && [ -n "$RATE" ] && [ -n "$SAMPLES" ] && [ -n "$ROOT" ] || { echo "atrium-postprocess: bad attest request, skipping"; rm -f "$req"; continue; }
    # Skip if already attested at the same rate+samples (nothing new to say).
    PREV=$(jq -r --arg id "$SKILL_ID" '.[$id] | "\(.successRate)/\(.sampleCount)"' "$ATTESTED" 2>/dev/null || echo "/")
    [ "$PREV" = "$RATE/$SAMPLES" ] && { echo "atrium-postprocess: $SKILL_ID already attested at $RATE/$SAMPLES"; rm -f "$req"; continue; }
    echo "atrium-postprocess: attesting $SKILL_ID — ${RATE}bps over $SAMPLES samples..."
    OUT=$(atrium attest "$SKILL_ID" --merkle-root "$ROOT" --success-rate "$RATE" --sample-count "$SAMPLES" --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: attest failed:"; echo "$OUT"; continue; }
    echo "$OUT"
    jq --arg id "$SKILL_ID" --argjson r "$RATE" --argjson s "$SAMPLES" --arg at "$(date -u +%FT%TZ)" \
      '.[$id] = {successRate:$r, sampleCount:$s, at:$at}' "$ATTESTED" > "$ATTESTED.tmp" && mv "$ATTESTED.tmp" "$ATTESTED"
    rm -f "$req"
  done
fi

# ── Publish requests queued by atrium-publish (.pending-atrium-publish/<slug>.json) ──
# Each request points at a staged skill dir (containing skill.md) the Claude step
# prepared. Publishing registers the skill on-chain (gas) AND pins to IPFS, so it needs
# both ATRIUM_PRIVATE_KEY and PINATA_JWT — neither is in the Claude step. `atrium publish`
# overwrites author_did to the local identity, so the staged manifest needs no DID.
PUB_DIR=".pending-atrium-publish"; PUBLISHED="memory/atrium/published.json"
if [ -d "$PUB_DIR" ] && ls -A "$PUB_DIR"/*.json >/dev/null 2>&1; then
  [ -f "$PUBLISHED" ] && jq empty "$PUBLISHED" 2>/dev/null || echo '{}' > "$PUBLISHED"
  for req in "$PUB_DIR"/*.json; do
    [ -f "$req" ] || continue
    SLUG=$(jq -r '.slug // empty' "$req"); SKPATH=$(jq -r '.path // empty' "$req")
    PRICE=$(jq -r '.price // "0.005"' "$req"); NETWORK=$(jq -r '.network // "base"' "$req")
    [ -n "$SLUG" ] && [ -n "$SKPATH" ] && [ -d "$SKPATH" ] || { echo "atrium-postprocess: bad publish request $(basename "$req"), skipping"; rm -f "$req"; continue; }
    jq -e --arg s "$SLUG" '.[$s].skillId // empty | select(length>0)' "$PUBLISHED" >/dev/null 2>&1 && { echo "atrium-postprocess: $SLUG already published"; rm -f "$req"; continue; }
    echo "atrium-postprocess: publishing $SLUG from $SKPATH at \$$PRICE on $NETWORK..."
    OUT=$(atrium publish "$SKPATH" --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: publish failed for $SLUG:"; echo "$OUT"; continue; }
    echo "$OUT"
    # Output labels (atrium publish): "Skill ID: 0x..", "IPFS CID: baf..", "Tx: 0x.."
    SKILL_ID=$(echo "$OUT" | grep -i 'Skill ID' | grep -oE '0x[a-fA-F0-9]{64}' | head -1 || echo "")
    CID=$(echo "$OUT" | grep -i 'IPFS CID' | grep -oE 'baf[a-z0-9]+' | head -1 || echo "")
    TX=$(echo "$OUT" | grep -iE '^[[:space:]]*Tx:' | grep -oE '0x[a-fA-F0-9]{64}' | head -1 || echo "")
    [ -n "$SKILL_ID" ] || { echo "atrium-postprocess: $SLUG published but skillId not parsed — leaving request for retry"; continue; }
    jq --arg s "$SLUG" --arg id "$SKILL_ID" --arg cid "$CID" --arg tx "$TX" --arg p "$PRICE" --arg at "$(date -u +%FT%TZ)" \
      '.[$s] = {skillId:$id, cid:$cid, tx:$tx, price:$p, at:$at}' "$PUBLISHED" > "$PUBLISHED.tmp" && mv "$PUBLISHED.tmp" "$PUBLISHED"
    echo "atrium-postprocess: recorded $SLUG -> $SKILL_ID"
    rm -f "$req"
  done
fi

# ── Withdraw queued by atrium-earnings (.pending-atrium-earnings/withdraw.json) ──
# Sweeping creator USDC is a tx (needs the key). `atrium withdraw` self-gates: it no-ops
# on a zero balance. We additionally honour a USDC threshold (don't bother below it).
WD_REQ=".pending-atrium-earnings/withdraw.json"; EARNINGS="memory/atrium/earnings.json"
if [ -f "$WD_REQ" ]; then
  NETWORK=$(jq -r '.network // "base"' "$WD_REQ"); THRESH=$(jq -r '.threshold // "1"' "$WD_REQ")
  OWED=$(atrium balance --network "$NETWORK" 2>/dev/null | grep -i 'Withdrawable' | grep -oE '[0-9]+\.?[0-9]*' | head -1 || echo "")
  if [ -z "$OWED" ]; then
    echo "atrium-postprocess: could not read withdrawable (no key / RPC?), skipping withdraw"
  elif awk -v o="$OWED" -v t="$THRESH" 'BEGIN{exit !(o+0 >= t+0)}'; then
    echo "atrium-postprocess: withdrawable \$$OWED >= threshold \$$THRESH on $NETWORK, withdrawing..."
    OUT=$(atrium withdraw --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: withdraw failed:"; echo "$OUT"; OUT=""; }
    echo "$OUT"
    TX=$(echo "$OUT" | grep -i 'Withdrew' | grep -oE '0x[a-fA-F0-9]{64}' | head -1 || echo "")
    if [ -n "$TX" ]; then
      [ -f "$EARNINGS" ] && jq -e 'type=="array"' "$EARNINGS" >/dev/null 2>&1 || echo '[]' > "$EARNINGS"
      jq --arg w "$OWED" --arg tx "$TX" --arg at "$(date -u +%FT%TZ)" \
        '. += [{date:$at, withdrawn:$w, tx:$tx}]' "$EARNINGS" > "$EARNINGS.tmp" && mv "$EARNINGS.tmp" "$EARNINGS"
      echo "atrium-postprocess: swept \$$OWED -> $TX"
      rm -f "$WD_REQ"
    fi
  else
    echo "atrium-postprocess: withdrawable \$$OWED < threshold \$$THRESH, leaving for next run"
    rm -f "$WD_REQ"
  fi
fi
echo "atrium-postprocess: done"
ATRIUM_SYNC_EOF_3
mkdir -p skills/atrium-publish
cat > skills/atrium-publish/SKILL.md <<'ATRIUM_SYNC_EOF_4'
---
name: atrium-publish
description: Publish the skills your agent created or evolved to Atrium — DID-signed, pinned to IPFS, priced per call in USDC — so they earn while you sleep
var: ""
tags: [crypto, atrium, skills, monetization]
---

> **${var}** — Optional: a single skill slug or queue path to publish this run. If empty, processes the whole publish queue.

Publishes designated local skills to **Atrium** (onchain skill marketplace, Base
mainnet) so they gain provenance + a per-call USDC price. The operator opts skills
in; this never publishes anything not explicitly queued.

Read `memory/MEMORY.md` for goals + voice.
Read `soul/SOUL.md` (if present) for identity (used in the published skill's framing).
Read `memory/atrium/publish-queue.md` — the opt-in list of skills to publish (one per line: `<skill-slug-or-path> [price_usdc]`).
Read `memory/atrium/published.json` — already-published skills (`{ slug: { skillId, cid, tx, price, at } }`) to avoid duplicates.
Read the last 7 days of `memory/logs/` for any skills the self-improve loop flagged as stable/high-quality (candidates to suggest queueing).

**Graceful bootstrap** — any of the above may be missing on a cold start. For each
missing/empty source, record `BOOTSTRAP: <resource> not yet populated` and continue.
Never fail the run.

## Steps

### 1. Detect mode
- **ATRIUM_PUBLISH_NO_QUEUE** — if `memory/atrium/publish-queue.md` is missing or empty AND no `var` input was given. Do not publish. Instead, scan recent logs + `skills/*/SKILL.md` for stable, reusable skills and propose 3–5 good publish candidates (slug + a one-line why + a suggested price), tell the operator how to queue them (append to `memory/atrium/publish-queue.md`), and stop.
- **ATRIUM_PUBLISH_OK** — otherwise.

### 2. Prepare only — do NOT spend in this step
Aeon keeps the wallet key (`ATRIUM_PRIVATE_KEY`) and `PINATA_JWT` **out of this
(model) step** by design, so `atrium publish` — which pins to IPFS *and* registers
on-chain — can never run inline here. This step **stages + queues**; the companion
`scripts/postprocess-atrium.sh` (which Aeon runs after the agent, with full env) does
the actual publish. Do not look for the secrets here and do not fail if they're
absent — just prepare the skill files and queue them.

### 3. Build the publish set
For each queue line (or the `var` input), resolve the target skill folder. Skip any slug
already in `published.json` (entry with a non-empty `skillId`) whose source is unchanged
(compare a content hash of its `SKILL.md`). For each remaining target, produce a valid
Atrium `skill.md`:
- frontmatter: `name`, `version` (bump if re-publishing an evolved version),
  `author_did: ''` (leave blank — `atrium publish` fills it from the wallet identity in
  post-process; never invent a DID), `description` (1–3 sentences),
  `tags`, `categories`, `language: en`, `runtime: prompt-only`,
  `price_per_call_usdc` (queue value, or `ATRIUM_DEFAULT_PRICE_USDC`, else `'0.005'`; must be > 0 and ≤ 50),
  `parent_skills: []` (or the prior version's skillId with a royalty if this is an evolution — see step 5),
  `created_at`, `derivation_method: hermes-loop`.
- body: the skill's actual instructions/prompt, cleaned for a third party (no secrets,
  no operator-specific paths). Never include "imported/scraped from" lines.

### 4. Stage + queue (do NOT publish here)
For each prepared skill, write its `skill.md` into a staging dir and **queue** it for
post-process — do **not** run `atrium publish` (no key/JWT in this step):
- write the manifest to `.pending-atrium-publish/<slug>/skill.md`
- write a request `.pending-atrium-publish/<slug>.json`:
  ```json
  { "slug": "<slug>", "path": ".pending-atrium-publish/<slug>", "price": "0.005", "network": "base" }
  ```
`scripts/postprocess-atrium.sh` then runs `atrium publish <path> --network <network>`
with the key present, captures `Skill ID` / `IPFS CID` / `Tx`, and records each result
to `memory/atrium/published.json` (skipping reverts like `ZeroPrice` / `SkillExists`).
Queue every opted-in skill; one publish per request, the script processes the batch.

### 5. Royalty lineage (evolutions)
If this is a newer version of a skill already in `published.json`, declare the prior
version as a parent (`parent_skills: [{ skill_id, royalty_bps }]`, e.g. 1000 = 10%)
so the lineage of an evolving skill is preserved and the prior version earns. Keep
combined parent royalties ≤ 50%.

### 6. Record + notify
The on-chain write + `published.json` append happen in post-process (where the key
is). In this step, append a dated line to `memory/logs/` listing what was **queued**
(slugs + prices), and notify the operator: how many skills were staged for publish and
that the post-process step will register them this run. If nothing was queued (all
duplicates), say so briefly.

## Notes
- This is the "earn from what you learn" loop: pair it with Aeon's self-improve so
  every stable, evolved skill becomes a provenance-signed, USDC-earning Atrium skill.
- Registry: `0xA713c88927523279B874640003Ed697e509732a7` (Base mainnet, verified).
  Docs: https://atriumhermes.tech/docs
ATRIUM_SYNC_EOF_4
mkdir -p skills/atrium-scout
cat > skills/atrium-scout/SKILL.md <<'ATRIUM_SYNC_EOF_5'
---
name: atrium-scout
description: Scan the Atrium marketplace for skills that match your agent's open loops and goals, then recommend (or invoke) the ones worth renting
var: ""
tags: [crypto, atrium, discovery, research]
---

> **${var}** — Optional focus (e.g. `pdf`, `trading`, `code-review`). If empty, scouts against all of your agent's current open loops.

Finds capabilities your agent *lacks* by searching **Atrium** (onchain skill
marketplace, Base) and surfacing skills that would unblock real work — instead of
building everything from scratch. Read-only by default; only invokes (pays) when
the operator explicitly enables it.

Read `memory/MEMORY.md` for goals + "Next Priorities".
Read the last 7 days of `memory/logs/` for recurring needs, failures, and "todo/next:" lines.
Read `memory/topics/*.md` for active threads.
Read `memory/cron-state.json` for skills failing repeatedly (a capability gap to fill).
Read `memory/atrium/scout-config.md` if present (`auto_invoke: true|false`, `max_price_usdc`, allowed categories).

**Graceful bootstrap** — for any missing/empty source, record
`BOOTSTRAP: <resource> not yet populated` and continue. Never fail.

## Steps

### 1. Build the need list
From the sources above, extract a deduped list of concrete capability needs (e.g.
"parse PDF tables", "review a PR", "summarize a thread"). Cap at 15. If a `var`
focus was given, prioritize needs touching it. If there are zero needs, switch to
**ATRIUM_SCOUT_BROWSE** mode: just surface the marketplace's top + newest skills as
inspiration, then stop.

### 2. Search Atrium
For each need, query the public indexer (no key required):
```bash
curl -s "https://indexer-production-92e5.up.railway.app/skills?q=<need>&sort=invocations&limit=5"
```
Collect candidates: `skillId`, `name`, `pricePerCall`, `tags`, `totalInvocations`.

### 3. Rank + recommend
For the top few candidates per need, fetch the full record to read its **quality
signals**:
```bash
curl -s "https://indexer-production-92e5.up.railway.app/skills/<skillId>"
  # .stakeAttestation = { rateBps, totalStake, attestationCount }  ← STRONGEST: a stake-weighted
  #                       success rate with $ATRIUM bonded behind it, slashable if false (sybil-resistant)
  # .attestation      = { successRate, sampleCount } | null         ← weaker: an unbacked claim anyone can post
```
Rank each candidate by relevance, then by quality in this order:
1. **Stake-backed rate** — a high `stakeAttestation.rateBps` with real `totalStake` bonded
   beats everything; the more $ATRIUM staked, the more trustworthy the number (it's
   slashable). `$ATRIUM` is 18-decimal — divide `totalStake` by 1e18 for the human amount.
2. **Plain attested** `successRate` over a real `sampleCount` (a signal, but unbacked).
3. **Proven usage** (`totalInvocations`) ÷ price as the tiebreaker.
Keep the best match per need that is genuinely useful (skip weak/irrelevant hits).
Produce a short table: need → recommended skill, price, quality (staked rate / attested / usage), why.

### 4. Optionally queue a rental (only if enabled)
If `scout-config.md` has `auto_invoke: true` AND a candidate's `pricePerCall` ≤
`max_price_usdc`: **queue** the single highest-value match by writing
`.pending-atrium/<slug>.json`:
```json
{ "skillId": "0x...", "slug": "<slug>", "price": "0.1", "network": "base" }
```
**Do NOT invoke here.** Aeon keeps the wallet key out of this (model) step, so
spending inline always fails. The companion `scripts/postprocess-atrium.sh` runs
after the agent — where `ATRIUM_PRIVATE_KEY` is available — and performs the actual
on-chain `atrium invoke`, then stashes the body under `memory/atrium/rented/<slug>.md`.
Queue at most ONE rental per run. Otherwise, recommend only.

### 5. Notify
Send the operator the ranked recommendations (need → skill → price → why), plus any
auto-invoked skill and where its body was saved. If nothing relevant was found,
say so in one line rather than padding.

## Notes
- Pairs with `atrium-publish`: scout what you need, publish what you build.
- Marketplace + docs: https://atriumhermes.tech · indexer is CORS-open and read-only.
ATRIUM_SYNC_EOF_5
mkdir -p skills/atrium-earnings
cat > skills/atrium-earnings/SKILL.md <<'ATRIUM_SYNC_EOF_6'
---
name: atrium-earnings
description: Track your Atrium creator earnings, withdraw USDC once it clears a threshold, and report it in the brief
var: ""
tags: [crypto, atrium, earnings, treasury]
---

> **${var}** — Optional: `report-only` to skip withdrawal this run (just report).

Keeps an eye on what your published Atrium skills are earning, sweeps the USDC to
your wallet when it's worth the gas, and folds the numbers into your daily brief —
closing the loop on a self-sustaining agent.

Read `memory/MEMORY.md` for context + voice.
Read `memory/atrium/published.json` for the skills you've published (to attribute earnings).
Read `memory/atrium/earnings.json` if present (rolling history: `{ date, withdrawable, withdrawnTotal, bySkill }`).

**Graceful bootstrap** — if `published.json` is missing/empty, there's nothing to
track yet: record `BOOTSTRAP: no published skills`, optionally note that
`atrium-publish` should run first, and stop. Never fail.

## Steps

### 1. Report from the indexer — no key in this step
Aeon keeps `ATRIUM_PRIVATE_KEY` **out of this (model) step**, so anything that reads
the wallet (`atrium balance`) or spends (`atrium withdraw`) can't run inline here. Use
the **indexer** for all reporting (no key needed); the actual sweep is queued for
post-process. Don't look for the key here and don't fail if it's absent.

### 2. Read earnings (indexer only)
Pull per-skill totals + lifetime earned for your published skillIds from the indexer
(`<your-address>` = the wallet on your `published.json` entries / the operator address):
```bash
curl -s "https://indexer-production-92e5.up.railway.app/creators/<your-address>/earnings"
```
Compute the delta vs the last entry in `earnings.json` (new invocations + new USDC
since the previous run). Withdrawable-but-unswept balance is read in post-process
(where the key lives) — report lifetime `totalEarned` from the indexer here.

### 3. Queue the withdraw (unless report-only)
Unless the `var` input is `report-only`, **queue** a sweep by writing
`.pending-atrium-earnings/withdraw.json`:
```json
{ "network": "base", "threshold": "1" }
```
(`threshold` = `ATRIUM_WITHDRAW_THRESHOLD_USDC`, default `1`.) **Do NOT run
`atrium withdraw` here.** `scripts/postprocess-atrium.sh` runs after the agent, reads
the on-chain withdrawable, and — if it's ≥ `threshold` — sweeps it (gas on Base is
sub-cent; `withdraw` no-ops on a zero balance), recording the tx to `earnings.json`.

### 4. Record + notify
Append a dated line to `memory/logs/` and the indexer-derived report (lifetime
`totalEarned`, new USDC since last run, `bySkill`) to your brief. The withdraw entry
(`{ date, withdrawn, tx }`) is appended to `memory/atrium/earnings.json` by
post-process when a sweep happens, so don't duplicate it here. Notify the operator
with: total earned to date, new USDC since last run, top-earning skill, and a note
that any due sweep runs in post-process. Keep it to a few lines — brief material,
not a wall of text.

## Notes
- Run after `atrium-publish` in a chain for a clean publish → earn → sweep loop.
- `withdraw()` only ever sends to your own wallet; one user's revert can't block it.
- The sweep happens in `scripts/postprocess-atrium.sh` (post-process step), where the
  wallet key is available — same pattern as `atrium-scout` and `atrium-publish`.
ATRIUM_SYNC_EOF_6
mkdir -p skills/atrium-attest
cat > skills/atrium-attest/SKILL.md <<'ATRIUM_SYNC_EOF_7'
---
name: atrium-attest
description: Turn this agent's real run-quality scores into onchain Atrium benchmark attestations for the skills it has published — a reputation signal the marketplace can rank by
var: ""
tags: [crypto, atrium, reputation, attestation]
---

> **`var`** — Optional: a single skill slug to attest. If empty, attests every eligible published skill.

Aeon already scores every skill run 1–5. This skill carries that signal **onchain**:
for each skill this agent has **published to Atrium** and actually **runs**, it posts
a benchmark attestation reflecting the skill's real, observed success rate — so
`atrium-scout` (and any consumer) can rank by *proven* quality, not just price or
invocation count.

It does NOT pay or attest inline (Aeon keeps the wallet key out of the model step):
it **queues** the attestation; `scripts/postprocess-atrium.sh` posts it after the run.

Read `memory/atrium/published.json` — the slug → `{ skillId, cid, ... }` map of skills
this agent published (written by `atrium-publish`). If missing/empty, record
`BOOTSTRAP: nothing published yet` and stop.

Read `memory/atrium/attested.json` if present — `{ skillId: { successRate, sampleCount, at } }`
already attested, to avoid re-posting an unchanged attestation.

## Steps

### 1. Build the attestation set
For each published slug, read `memory/skill-health/<slug>.json`
(`avg_score` is a rolling 1–5 mean; `history` is the per-run score list). Keep only
skills with **at least 3 runs** (`history` length ≥ 3) — fewer is too noisy to attest.
If a skill maps to a `skillId` in `published.json`, it is eligible.

### 2. Compute the signal
For each eligible skill:
- `successRate` (bps, 0–10000) = `round(avg_score / 5 * 10000)`.
- `sampleCount` = number of runs in `history`.
- `merkleRoot` = a deterministic reference hash for this usage attestation, e.g.
  `keccak256("aeon-runs:" + skillId + ":" + sampleCount + ":" + successRate)`. This is
  a **usage** attestation (real run-quality), not a formal benchmark suite — be honest
  about that in the report.
- Skip if `attested.json` already has this skillId at the same `successRate` + `sampleCount`
  (nothing new to say).

### 3. Queue the attestations (do NOT post inline)
Write one file per skill to `.pending-atrium-attest/<slug>.json`:
```json
{ "skillId": "0x...", "slug": "<slug>", "successRate": 8400, "sampleCount": 12, "merkleRoot": "0x...", "network": "base" }
```
`scripts/postprocess-atrium.sh` performs the on-chain `atrium attest` afterwards
(where `ATRIUM_PRIVATE_KEY` is available), and records the result in
`memory/atrium/attested.json`.

### 4. Notify
Report the skills queued for attestation (slug → success rate → samples), and note
that the on-chain post happens in post-process. If nothing was eligible, say so in one line.

## Notes
- Pairs with `atrium-publish` (publish what you build) and `atrium-scout` (rank by
  attested quality). The honest signal here is *this agent's* run experience; on a
  permissionless registry the latest attestation wins, so attest only your own published
  skills from real runs.
- Marketplace + docs: https://atriumhermes.tech
ATRIUM_SYNC_EOF_7
chmod +x scripts/postprocess-atrium.sh 2>/dev/null || true
echo
echo "Pack files written. Verify + push:"
echo "  grep -rnE '\`[^\`]*\$[^\`]*\`' skills/*/SKILL.md   # scanner check, should be empty"
echo "  git add -A && git commit -m 'Sync pack: post-process spend + atrium-attest (reputation) + scanner-clean' && git push"

