#!/usr/bin/env bash
set -euo pipefail
#
# sync-pack.sh — write the canonical aeon-atrium-skills pack into THIS repo, then
# commit + push. Run from the root of a clone/codespace of
# Atrium-Hermes/aeon-atrium-skills:  bash sync-pack.sh
#
# Full snapshot (idempotent): brings the live pack to exactly match upstream source,
# including the post-process spend pattern, scanner-clean SKILL.md, and atrium-attest.
[ -f skills-pack.json ] || { echo "Run from the root of the aeon-atrium-skills pack repo." >&2; exit 1; }

cat > LICENSE <<'ATRIUM_SYNC_EOF_0'
MIT License

Copyright (c) 2026 Atrium-Hermes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
ATRIUM_SYNC_EOF_0
cat > README.md <<'ATRIUM_SYNC_EOF_1'
# Atrium Skills — an Aeon skill pack

Publish, monetize, and discover agent skills on **[Atrium](https://atriumhermes.tech)**
— the onchain skill marketplace on Base — straight from an [Aeon](https://www.aeon.fun)
agent. Turn the skills your agent evolves into provenance-signed, USDC-earning assets,
and rent the ones it's missing.

## Install
```bash
./install-skill-pack <your-github-owner>/aeon-atrium-skills
```
Skills install **disabled by default** — enable the ones you want in `aeon.yml`.

## Skills
| Skill | What it does | Schedule | Secrets |
|---|---|---|---|
| `atrium-publish` | Publish queued/evolved skills to Atrium (DID-signed, IPFS, priced in USDC) so they earn per call. Declares prior versions as royalty parents for evolutions. | `0 13 * * *` | `ATRIUM_PRIVATE_KEY`, `PINATA_JWT` |
| `atrium-scout` | Search Atrium for skills matching your open loops/goals; recommend (or, if enabled, invoke) what's worth renting. Read-only by default. | `0 11 * * *` | optional `ATRIUM_PRIVATE_KEY` |
| `atrium-earnings` | Track creator earnings and **auto-withdraw USDC daily** when withdrawable ≥ `ATRIUM_WITHDRAW_THRESHOLD_USDC` (default `1`); folds totals into the brief. Set the threshold before enabling, or pass `report-only` to skip the sweep. | `0 14 * * *` | `ATRIUM_PRIVATE_KEY` |
| `atrium-attest` | Turn this agent's real 1–5 run-quality scores into **onchain benchmark attestations** for the skills it published — a reputation signal `atrium-scout` (and the marketplace) can rank by. Queues; the tx runs in post-process. | `0 15 * * 1` | `ATRIUM_PRIVATE_KEY` |

Chain them for a self-sustaining loop: **scout → publish → earnings → attest** (discover, monetize, sweep, and prove quality onchain).

## Secrets
- `ATRIUM_PRIVATE_KEY` — the agent's EVM key (its Atrium wallet; needs a little Base ETH for gas + USDC to invoke). Generated by `atrium init`.
- `PINATA_JWT` — IPFS pinning JWT (publish only). Free at pinata.cloud.
- Optional: `ATRIUM_DEFAULT_PRICE_USDC`, `ATRIUM_WITHDRAW_THRESHOLD_USDC`.

The skills install the `atrium` CLI on first run from npm, pinned to a published
version: `npm i -g @atrium-hermes/cli@0.1.0` (no live curl-pipe-bash). They
read/write `~/.atrium/.env`. Discovery uses the public, read-only indexer API (no key).

## Spending: the post-process step (required for renting)

Aeon deliberately keeps secrets **out of the Claude/model step**, so a skill cannot
spend (`atrium invoke`) inline — the wallet key isn't there. `atrium-scout` therefore
**queues** its top pick to `.pending-atrium/<slug>.json`, and the actual on-chain
spend happens afterwards in **`scripts/postprocess-atrium.sh`** (Aeon auto-runs
`scripts/postprocess-*.sh` after Claude, with full env). Two one-time setup steps:

1. **Copy the script** `scripts/postprocess-atrium.sh` (shipped in this pack) into your
   Aeon repo at the same path. It no-ops when no key is set (report-only), honours
   `auto_invoke` + `max_price_usdc`, and rents at most one skill per run.
2. **Wire the key into the post-process step** in `.github/workflows/aeon.yml` — add to
   that step's `env:` (NOT the Claude step):
   ```yaml
   ATRIUM_PRIVATE_KEY: ${{ secrets.ATRIUM_PRIVATE_KEY }}
   # PINATA_JWT: ${{ secrets.PINATA_JWT }}   # also, if you publish
   ```

Then set `auto_invoke: true` in `memory/atrium/scout-config.md` once the wallet is
funded. (`atrium-publish` / `atrium-earnings` also spend on-chain and want the same
post-process treatment — moving their spend into post-process scripts is the same pattern.)

## How it composes with Aeon
Aeon generates and evolves skills; Atrium gives them identity, a market, and a
revenue line. `atrium-publish` is the "earn from what you learn" loop — every stable
skill from Aeon's self-improve cycle becomes a USDC-earning, onchain asset, with the
prior version earning royalties on its descendants.

## Links
- Atrium: https://atriumhermes.tech · docs `/docs` · whitepaper `/whitepaper`
- Registry (Base mainnet, verified): `0xA713c88927523279B874640003Ed697e509732a7`
- Aeon: https://www.aeon.fun · https://github.com/aaronjmars/aeon

MIT.
ATRIUM_SYNC_EOF_1
cat > skills-pack.json <<'ATRIUM_SYNC_EOF_2'
{
  "name": "Atrium Skills",
  "version": "0.1.0",
  "description": "Publish, monetize, and discover agent skills on Atrium — the onchain skill marketplace on Base. Turn an Aeon agent's evolving skills into provenance-signed, USDC-earning assets.",
  "author": "Atrium-Hermes",
  "license": "MIT",
  "homepage": "https://atriumhermes.tech",
  "skills": [
    {
      "slug": "atrium-publish",
      "path": "skills/atrium-publish",
      "description": "Publish skills your agent created or evolved to Atrium — DID-signed, pinned to IPFS, priced in USDC — so they earn per call.",
      "category": "crypto",
      "schedule": "0 13 * * *",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY", "PINATA_JWT"],
      "secrets_optional": ["ATRIUM_DEFAULT_PRICE_USDC"],
      "capabilities": ["onchain_writes", "external_api", "writes_external_host"]
    },
    {
      "slug": "atrium-scout",
      "path": "skills/atrium-scout",
      "description": "Scan the Atrium marketplace for skills that match your agent's open loops and goals, and recommend (or invoke) the ones worth renting.",
      "category": "crypto",
      "schedule": "0 11 * * *",
      "default_enabled": false,
      "secrets_optional": ["ATRIUM_PRIVATE_KEY"],
      "capabilities": ["external_api", "read_only"]
    },
    {
      "slug": "atrium-earnings",
      "path": "skills/atrium-earnings",
      "description": "Track your Atrium creator earnings, withdraw USDC once it clears a threshold, and report it in the brief. Note: runs daily and AUTO-WITHDRAWS to your wallet whenever withdrawable ≥ ATRIUM_WITHDRAW_THRESHOLD_USDC (default 1) — set this env var before enabling to control sweep frequency, or pass `report-only` to skip withdrawal. Withdraw only ever sends to your own wallet.",
      "category": "crypto",
      "schedule": "0 14 * * *",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY"],
      "secrets_optional": ["ATRIUM_WITHDRAW_THRESHOLD_USDC"],
      "capabilities": ["onchain_writes", "sends_notifications"]
    },
    {
      "slug": "atrium-attest",
      "path": "skills/atrium-attest",
      "description": "Turn this agent's real 1-5 run-quality scores into onchain Atrium benchmark attestations for the skills it published — a reputation signal the marketplace can rank by. Queues the attestation; the spend/tx runs in scripts/postprocess-atrium.sh (key stays out of the model step).",
      "category": "crypto",
      "schedule": "0 15 * * 1",
      "default_enabled": false,
      "secrets_required": ["ATRIUM_PRIVATE_KEY"],
      "capabilities": ["onchain_writes"]
    }
  ]
}
ATRIUM_SYNC_EOF_2
mkdir -p scripts
cat > scripts/postprocess-atrium.sh <<'ATRIUM_SYNC_EOF_3'
#!/usr/bin/env bash
# Post-process Atrium rental requests queued by the atrium-scout skill.
#
# WHY THIS EXISTS: Aeon keeps secrets (ATRIUM_PRIVATE_KEY) OUT of the Claude/model
# step by design, so a skill can't spend inline. Instead atrium-scout writes its
# top pick to .pending-atrium/<slug>.json, and THIS script — which Aeon runs after
# Claude (via the post-process step, with full env) — performs the on-chain
# `atrium invoke` (USDC spend) and stashes the body.
#
# SETUP (one-time, in your Aeon repo):
#   1. Copy this file to scripts/postprocess-atrium.sh (Aeon auto-runs scripts/postprocess-*.sh).
#   2. Add to the post-process step env in .github/workflows/aeon.yml:
#        ATRIUM_PRIVATE_KEY: ${{ secrets.ATRIUM_PRIVATE_KEY }}
#      (keep it OUT of the Claude step — model never sees the key.)
#
# Safety: no key -> no-op (report-only). Honours auto_invoke + max_price_usdc from
# memory/atrium/scout-config.md. Skips already-rented skills. One rental per run.
set -euo pipefail

PENDING_DIR=".pending-atrium"
RENTED_DIR="memory/atrium/rented"
CONFIG="memory/atrium/scout-config.md"

[ -d "$PENDING_DIR" ] && ls -A "$PENDING_DIR"/*.json >/dev/null 2>&1 || { echo "atrium-postprocess: no pending requests"; exit 0; }
[ -n "${ATRIUM_PRIVATE_KEY:-}" ] || { echo "atrium-postprocess: ATRIUM_PRIVATE_KEY not set, skipping (report-only)"; exit 0; }

AUTO_INVOKE="false"; MAX_PRICE="0"
if [ -f "$CONFIG" ]; then
  AUTO_INVOKE=$(grep -E '^auto_invoke:' "$CONFIG" | head -1 | sed -E 's/^auto_invoke:[[:space:]]*//; s/[[:space:]]*#.*//' || echo false)
  MAX_PRICE=$(grep -E '^max_price_usdc:' "$CONFIG" | head -1 | sed -E 's/^max_price_usdc:[[:space:]]*//; s/[[:space:]]*#.*//' || echo 0)
fi
[ "$AUTO_INVOKE" = "true" ] || { echo "atrium-postprocess: auto_invoke is '$AUTO_INVOKE', not renting"; exit 0; }

command -v atrium >/dev/null 2>&1 || { echo "atrium-postprocess: installing atrium CLI..."; npm install -g @atrium-hermes/cli >/dev/null 2>&1 || { echo "atrium-postprocess: CLI install failed"; exit 0; }; }

mkdir -p "$RENTED_DIR"
for req in "$PENDING_DIR"/*.json; do
  [ -f "$req" ] || continue
  SKILL_ID=$(jq -r '.skillId // empty' "$req"); SLUG=$(jq -r '.slug // empty' "$req")
  PRICE=$(jq -r '.price // "0"' "$req"); NETWORK=$(jq -r '.network // "base"' "$req")
  [ -n "$SKILL_ID" ] && [ -n "$SLUG" ] || { echo "atrium-postprocess: bad request $(basename "$req"), skipping"; continue; }
  [ -f "$RENTED_DIR/$SLUG.md" ] && { echo "atrium-postprocess: $SLUG already rented"; rm -f "$req"; continue; }
  awk -v p="$PRICE" -v c="$MAX_PRICE" 'BEGIN{exit !(p+0 > c+0)}' && { echo "atrium-postprocess: $SLUG price $PRICE > cap $MAX_PRICE, skipping"; continue; }

  echo "atrium-postprocess: invoking $SLUG ($SKILL_ID) at \$$PRICE on $NETWORK..."
  # Balance/allowance are enforced on-chain by invoke (it reverts if short), so we
  # don't pre-gate on `atrium balance` (its non-zero exit must never block a funded wallet).
  atrium balance --network "$NETWORK" 2>/dev/null || echo "atrium-postprocess: balance query unavailable, proceeding (invoke enforces funds on-chain)"
  OUT=$(atrium invoke "$SKILL_ID" --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: invoke failed for $SLUG:"; echo "$OUT"; continue; }
  echo "$OUT"
  TX=$(echo "$OUT" | grep -oE '0x[a-fA-F0-9]{64}' | head -1 || echo "")
  BODY=$(atrium fetch "$SKILL_ID" --network "$NETWORK" 2>/dev/null || echo "")
  { echo "# $SLUG (rented from Atrium)"; echo; echo "- skillId: \`$SKILL_ID\`"; echo "- price: \$$PRICE USDC"; echo "- tx: ${TX:-see run logs}"; echo; echo "---"; echo; echo "$BODY"; } > "$RENTED_DIR/$SLUG.md"
  echo "atrium-postprocess: saved body to $RENTED_DIR/$SLUG.md"
  rm -f "$req"
  break   # one rental per run
done

# ── Reputation attestations queued by atrium-attest (.pending-atrium-attest/*.json) ──
# These are tx-only (no USDC spend) but need ETH for gas; safe to run unconditionally.
ATTEST_DIR=".pending-atrium-attest"; ATTESTED="memory/atrium/attested.json"
if [ -d "$ATTEST_DIR" ] && ls -A "$ATTEST_DIR"/*.json >/dev/null 2>&1; then
  [ -f "$ATTESTED" ] && jq empty "$ATTESTED" 2>/dev/null || echo '{}' > "$ATTESTED"
  for req in "$ATTEST_DIR"/*.json; do
    [ -f "$req" ] || continue
    SKILL_ID=$(jq -r '.skillId // empty' "$req"); RATE=$(jq -r '.successRate // empty' "$req")
    SAMPLES=$(jq -r '.sampleCount // empty' "$req"); ROOT=$(jq -r '.merkleRoot // empty' "$req")
    NETWORK=$(jq -r '.network // "base"' "$req")
    [ -n "$SKILL_ID" ] && [ -n "$RATE" ] && [ -n "$SAMPLES" ] && [ -n "$ROOT" ] || { echo "atrium-postprocess: bad attest request, skipping"; rm -f "$req"; continue; }
    # Skip if already attested at the same rate+samples (nothing new to say).
    PREV=$(jq -r --arg id "$SKILL_ID" '.[$id] | "\(.successRate)/\(.sampleCount)"' "$ATTESTED" 2>/dev/null || echo "/")
    [ "$PREV" = "$RATE/$SAMPLES" ] && { echo "atrium-postprocess: $SKILL_ID already attested at $RATE/$SAMPLES"; rm -f "$req"; continue; }
    echo "atrium-postprocess: attesting $SKILL_ID — ${RATE}bps over $SAMPLES samples..."
    OUT=$(atrium attest "$SKILL_ID" --merkle-root "$ROOT" --success-rate "$RATE" --sample-count "$SAMPLES" --network "$NETWORK" 2>&1) || { echo "atrium-postprocess: attest failed:"; echo "$OUT"; continue; }
    echo "$OUT"
    jq --arg id "$SKILL_ID" --argjson r "$RATE" --argjson s "$SAMPLES" --arg at "$(date -u +%FT%TZ)" \
      '.[$id] = {successRate:$r, sampleCount:$s, at:$at}' "$ATTESTED" > "$ATTESTED.tmp" && mv "$ATTESTED.tmp" "$ATTESTED"
    rm -f "$req"
  done
fi
echo "atrium-postprocess: done"
ATRIUM_SYNC_EOF_3
mkdir -p skills/atrium-publish
cat > skills/atrium-publish/SKILL.md <<'ATRIUM_SYNC_EOF_4'
---
name: atrium-publish
description: Publish the skills your agent created or evolved to Atrium — DID-signed, pinned to IPFS, priced per call in USDC — so they earn while you sleep
var: ""
tags: [crypto, atrium, skills, monetization]
---

> **${var}** — Optional: a single skill slug or queue path to publish this run. If empty, processes the whole publish queue.

Publishes designated local skills to **Atrium** (onchain skill marketplace, Base
mainnet) so they gain provenance + a per-call USDC price. The operator opts skills
in; this never publishes anything not explicitly queued.

Read `memory/MEMORY.md` for goals + voice.
Read `soul/SOUL.md` (if present) for identity (used in the published skill's framing).
Read `memory/atrium/publish-queue.md` — the opt-in list of skills to publish (one per line: `<skill-slug-or-path> [price_usdc]`).
Read `memory/atrium/published.json` — already-published skills (`{ slug: { skillId, cid, tx, price, at } }`) to avoid duplicates.
Read the last 7 days of `memory/logs/` for any skills the self-improve loop flagged as stable/high-quality (candidates to suggest queueing).

**Graceful bootstrap** — any of the above may be missing on a cold start. For each
missing/empty source, record `BOOTSTRAP: <resource> not yet populated` and continue.
Never fail the run.

## Steps

### 1. Detect mode
- **ATRIUM_PUBLISH_NO_QUEUE** — if `memory/atrium/publish-queue.md` is missing or empty AND no `var` input was given. Do not publish. Instead, scan recent logs + `skills/*/SKILL.md` for stable, reusable skills and propose 3–5 good publish candidates (slug + a one-line why + a suggested price), tell the operator how to queue them (append to `memory/atrium/publish-queue.md`), and stop.
- **ATRIUM_PUBLISH_OK** — otherwise.

### 2. Ensure the Atrium CLI
Check `command -v atrium`. If missing, install the pinned, published CLI from npm:
```bash
npm i -g @atrium-hermes/cli@0.1.0
```
Confirm `~/.atrium/.env` has `ATRIUM_PRIVATE_KEY` (from the `ATRIUM_PRIVATE_KEY`
secret), `ATRIUM_NETWORK=base`, `ATRIUM_REGISTRY_MAINNET=0xA713c88927523279B874640003Ed697e509732a7`,
and `PINATA_JWT` (from the `PINATA_JWT` secret). Write any missing values. If
`ATRIUM_PRIVATE_KEY` or `PINATA_JWT` is unset, record `BOOTSTRAP: secrets missing`,
notify the operator, and stop (do not invent keys).

### 3. Build the publish set
For each queue line (or the `var` input), resolve the target skill folder. Skip any slug
already in `published.json` whose source is unchanged (compare a content hash of
its `SKILL.md`). For each remaining target, produce a valid Atrium `skill.md`:
- frontmatter: `name`, `version` (bump if re-publishing an evolved version),
  `author_did` (from `atrium init`), `description` (1–3 sentences),
  `tags`, `categories`, `language: en`, `runtime: prompt-only`,
  `price_per_call_usdc` (queue value, or `ATRIUM_DEFAULT_PRICE_USDC`, else `'0.005'`; must be > 0 and ≤ 50),
  `parent_skills: []` (or the prior version's skillId with a royalty if this is an evolution — see step 5),
  `created_at`, `derivation_method: hermes-loop`.
- body: the skill's actual instructions/prompt, cleaned for a third party (no secrets,
  no operator-specific paths). Never include "imported/scraped from" lines.

### 4. Publish
For each prepared skill:
```bash
atrium publish <path-to-skill-dir> --network base
```
Capture the `Skill ID`, `IPFS CID`, and `Tx`. On revert (`ZeroPrice`, `SkillExists`,
insufficient gas), log the reason and continue with the rest — never abort the batch.

### 5. Royalty lineage (evolutions)
If this is a newer version of a skill already in `published.json`, declare the prior
version as a parent (`parent_skills: [{ skill_id, royalty_bps }]`, e.g. 1000 = 10%)
so the lineage of an evolving skill is preserved and the prior version earns. Keep
combined parent royalties ≤ 50%.

### 6. Record + notify
Append each result to `memory/atrium/published.json`. Append a dated line to
`memory/logs/`. Notify the operator: how many skills published, their names +
skillIds + a Basescan/atriumhermes.tech link, and the prices set. If nothing was
published (all duplicates), say so briefly.

## Notes
- This is the "earn from what you learn" loop: pair it with Aeon's self-improve so
  every stable, evolved skill becomes a provenance-signed, USDC-earning Atrium skill.
- Registry: `0xA713c88927523279B874640003Ed697e509732a7` (Base mainnet, verified).
  Docs: https://atriumhermes.tech/docs
ATRIUM_SYNC_EOF_4
mkdir -p skills/atrium-scout
cat > skills/atrium-scout/SKILL.md <<'ATRIUM_SYNC_EOF_5'
---
name: atrium-scout
description: Scan the Atrium marketplace for skills that match your agent's open loops and goals, then recommend (or invoke) the ones worth renting
var: ""
tags: [crypto, atrium, discovery, research]
---

> **${var}** — Optional focus (e.g. `pdf`, `trading`, `code-review`). If empty, scouts against all of your agent's current open loops.

Finds capabilities your agent *lacks* by searching **Atrium** (onchain skill
marketplace, Base) and surfacing skills that would unblock real work — instead of
building everything from scratch. Read-only by default; only invokes (pays) when
the operator explicitly enables it.

Read `memory/MEMORY.md` for goals + "Next Priorities".
Read the last 7 days of `memory/logs/` for recurring needs, failures, and "todo/next:" lines.
Read `memory/topics/*.md` for active threads.
Read `memory/cron-state.json` for skills failing repeatedly (a capability gap to fill).
Read `memory/atrium/scout-config.md` if present (`auto_invoke: true|false`, `max_price_usdc`, allowed categories).

**Graceful bootstrap** — for any missing/empty source, record
`BOOTSTRAP: <resource> not yet populated` and continue. Never fail.

## Steps

### 1. Build the need list
From the sources above, extract a deduped list of concrete capability needs (e.g.
"parse PDF tables", "review a PR", "summarize a thread"). Cap at 15. If a `var`
focus was given, prioritize needs touching it. If there are zero needs, switch to
**ATRIUM_SCOUT_BROWSE** mode: just surface the marketplace's top + newest skills as
inspiration, then stop.

### 2. Search Atrium
For each need, query the public indexer (no key required):
```bash
curl -s "https://indexer-production-92e5.up.railway.app/skills?q=<need>&sort=invocations&limit=5"
```
Collect candidates: `skillId`, `name`, `pricePerCall`, `tags`, `totalInvocations`.

### 3. Rank + recommend
For the top few candidates per need, fetch the full record to read any **onchain
attestation** (real quality signal):
```bash
curl -s "https://indexer-production-92e5.up.railway.app/skills/<skillId>"   # .attestation = { successRate, sampleCount } | null
```
Score each candidate by relevance × proven usage (`totalInvocations`) ÷ price, then
**boost by attested success rate when present** (a skill with a high attested
`successRate` over a real `sampleCount` outranks an unattested one at similar usage).
Keep the best match per need that is genuinely useful (skip weak/irrelevant hits).
Produce a short table: need → recommended skill, price, attested quality (if any), why.

### 4. Optionally queue a rental (only if enabled)
If `scout-config.md` has `auto_invoke: true` AND a candidate's `pricePerCall` ≤
`max_price_usdc`: **queue** the single highest-value match by writing
`.pending-atrium/<slug>.json`:
```json
{ "skillId": "0x...", "slug": "<slug>", "price": "0.1", "network": "base" }
```
**Do NOT invoke here.** Aeon keeps the wallet key out of this (model) step, so
spending inline always fails. The companion `scripts/postprocess-atrium.sh` runs
after the agent — where `ATRIUM_PRIVATE_KEY` is available — and performs the actual
on-chain `atrium invoke`, then stashes the body under `memory/atrium/rented/<slug>.md`.
Queue at most ONE rental per run. Otherwise, recommend only.

### 5. Notify
Send the operator the ranked recommendations (need → skill → price → why), plus any
auto-invoked skill and where its body was saved. If nothing relevant was found,
say so in one line rather than padding.

## Notes
- Pairs with `atrium-publish`: scout what you need, publish what you build.
- Marketplace + docs: https://atriumhermes.tech · indexer is CORS-open and read-only.
ATRIUM_SYNC_EOF_5
mkdir -p skills/atrium-earnings
cat > skills/atrium-earnings/SKILL.md <<'ATRIUM_SYNC_EOF_6'
---
name: atrium-earnings
description: Track your Atrium creator earnings, withdraw USDC once it clears a threshold, and report it in the brief
var: ""
tags: [crypto, atrium, earnings, treasury]
---

> **${var}** — Optional: `report-only` to skip withdrawal this run (just report).

Keeps an eye on what your published Atrium skills are earning, sweeps the USDC to
your wallet when it's worth the gas, and folds the numbers into your daily brief —
closing the loop on a self-sustaining agent.

Read `memory/MEMORY.md` for context + voice.
Read `memory/atrium/published.json` for the skills you've published (to attribute earnings).
Read `memory/atrium/earnings.json` if present (rolling history: `{ date, withdrawable, withdrawnTotal, bySkill }`).

**Graceful bootstrap** — if `published.json` is missing/empty, there's nothing to
track yet: record `BOOTSTRAP: no published skills`, optionally note that
`atrium-publish` should run first, and stop. Never fail.

## Steps

### 1. Ensure the CLI + wallet
`command -v atrium` or install the pinned, published CLI from npm: `npm i -g @atrium-hermes/cli@0.1.0`.
Confirm `~/.atrium/.env` has `ATRIUM_PRIVATE_KEY` (secret), `ATRIUM_NETWORK=base`,
`ATRIUM_REGISTRY_MAINNET=0xA713c88927523279B874640003Ed697e509732a7`. If the key is
missing, record `BOOTSTRAP: ATRIUM_PRIVATE_KEY missing`, notify, and stop.

### 2. Read earnings
```bash
atrium balance        # shows withdrawable USDC for your wallet
```
Also pull per-skill totals for your published skillIds from the indexer:
```bash
curl -s "https://indexer-production-92e5.up.railway.app/creators/<your-address>/earnings"
```
Compute the delta vs the last entry in `earnings.json` (new invocations + new USDC
since the previous run).

### 3. Withdraw (unless report-only)
Let `T = ATRIUM_WITHDRAW_THRESHOLD_USDC` (default `1`). If withdrawable ≥ `T` and
the `var` input is not `report-only`:
```bash
atrium withdraw --network base
```
Capture the tx hash. Gas on Base is sub-cent, so a low threshold is fine. On revert
(`NothingToWithdraw`), skip silently.

### 4. Record + notify
Append today's `{ date, withdrawable, withdrawnTotal, bySkill }` to
`memory/atrium/earnings.json` and a dated line to `memory/logs/`. Notify the
operator with: total earned to date, new USDC since last run, top-earning skill,
and any withdrawal tx. Keep it to a few lines — this is brief material, not a wall
of text.

## Notes
- Run after `atrium-publish` in a chain for a clean publish → earn → sweep loop.
- `withdraw()` only ever sends to your own wallet; one user's revert can't block it.
ATRIUM_SYNC_EOF_6
mkdir -p skills/atrium-attest
cat > skills/atrium-attest/SKILL.md <<'ATRIUM_SYNC_EOF_7'
---
name: atrium-attest
description: Turn this agent's real run-quality scores into onchain Atrium benchmark attestations for the skills it has published — a reputation signal the marketplace can rank by
var: ""
tags: [crypto, atrium, reputation, attestation]
---

> **`var`** — Optional: a single skill slug to attest. If empty, attests every eligible published skill.

Aeon already scores every skill run 1–5. This skill carries that signal **onchain**:
for each skill this agent has **published to Atrium** and actually **runs**, it posts
a benchmark attestation reflecting the skill's real, observed success rate — so
`atrium-scout` (and any consumer) can rank by *proven* quality, not just price or
invocation count.

It does NOT pay or attest inline (Aeon keeps the wallet key out of the model step):
it **queues** the attestation; `scripts/postprocess-atrium.sh` posts it after the run.

Read `memory/atrium/published.json` — the slug → `{ skillId, cid, ... }` map of skills
this agent published (written by `atrium-publish`). If missing/empty, record
`BOOTSTRAP: nothing published yet` and stop.

Read `memory/atrium/attested.json` if present — `{ skillId: { successRate, sampleCount, at } }`
already attested, to avoid re-posting an unchanged attestation.

## Steps

### 1. Build the attestation set
For each published slug, read `memory/skill-health/<slug>.json`
(`avg_score` is a rolling 1–5 mean; `history` is the per-run score list). Keep only
skills with **at least 3 runs** (`history` length ≥ 3) — fewer is too noisy to attest.
If a skill maps to a `skillId` in `published.json`, it is eligible.

### 2. Compute the signal
For each eligible skill:
- `successRate` (bps, 0–10000) = `round(avg_score / 5 * 10000)`.
- `sampleCount` = number of runs in `history`.
- `merkleRoot` = a deterministic reference hash for this usage attestation, e.g.
  `keccak256("aeon-runs:" + skillId + ":" + sampleCount + ":" + successRate)`. This is
  a **usage** attestation (real run-quality), not a formal benchmark suite — be honest
  about that in the report.
- Skip if `attested.json` already has this skillId at the same `successRate` + `sampleCount`
  (nothing new to say).

### 3. Queue the attestations (do NOT post inline)
Write one file per skill to `.pending-atrium-attest/<slug>.json`:
```json
{ "skillId": "0x...", "slug": "<slug>", "successRate": 8400, "sampleCount": 12, "merkleRoot": "0x...", "network": "base" }
```
`scripts/postprocess-atrium.sh` performs the on-chain `atrium attest` afterwards
(where `ATRIUM_PRIVATE_KEY` is available), and records the result in
`memory/atrium/attested.json`.

### 4. Notify
Report the skills queued for attestation (slug → success rate → samples), and note
that the on-chain post happens in post-process. If nothing was eligible, say so in one line.

## Notes
- Pairs with `atrium-publish` (publish what you build) and `atrium-scout` (rank by
  attested quality). The honest signal here is *this agent's* run experience; on a
  permissionless registry the latest attestation wins, so attest only your own published
  skills from real runs.
- Marketplace + docs: https://atriumhermes.tech
ATRIUM_SYNC_EOF_7
chmod +x scripts/postprocess-atrium.sh 2>/dev/null || true
echo
echo "Pack files written. Verify + push:"
echo "  grep -rnE '\`[^\`]*\$[^\`]*\`' skills/*/SKILL.md   # scanner check, should be empty"
echo "  git add -A && git commit -m 'Sync pack: post-process spend + atrium-attest (reputation) + scanner-clean' && git push"

